name: JAVA CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        id: docker_build
        run: docker build -t dotoapiimage .
